# Site settings
title: FengMichel's Blog
description: 'My blog using Jekyll-Uno'
url: 'http://fengzhongshuang.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'fengzhongshuang'
  email: fengzhongshuang@gmail.com
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  github_username:  fengzhongshuang
  # linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
